In [8]:
pip install CBFV

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Collecting CBFV
  Downloading CBFV-1.1.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: numpy in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from CBFV) (1.26.4)
Requirement already satisfied: pandas in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from CBFV) (2.3.3)
Requirement already satisfied: tqdm in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from CBFV) (4.67.3)
Requirement already satisfied: pytest in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from CBFV) (8.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas->CBFV) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas->CBFV) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas->CBFV) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->CBFV) (1.17.0)
Requirement already satisfied: iniconfig>=1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pytest->CBFV) (2.1.0)
Requirement already satisfied: packaging>=20 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pytest->CBFV) (25.0)
Requirement already satisfied: pluggy<2,>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pytest->CBFV) (1.5.0)
Requirement already satisfied: pygments>=2.7.2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pytest->CBFV) (2.19.2)
Downloading CBFV-1.1.0-py3-none-any.whl (539 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 539.2/539.2 kB 2.9 MB/s  0:00:00
Installing collected packages: CBFV
Successfully installed CBFV-1.1.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install matminer

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Collecting matminer
  Using cached matminer-0.10.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: numpy>=1.23 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matminer) (1.26.4)
Requirement already satisfied: requests~=2.31 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from matminer) (2.34.2)
Requirement already satisfied: pandas<3,>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matminer) (2.3.3)
Requirement already satisfied: tqdm~=4.66 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from matminer) (4.67.3)
Collecting pymongo~=4.5 (from matminer)
  Using cached pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Requirement already satisfied: scikit-learn~=1.3 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matminer) (1.7.2)
Requirement already satisfied: sympy~=1.11 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matminer) (1.14.0)
Requirement already satisfied: monty>=2023 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from matminer) (2026.5.18)
Requirement already satisfied: pymatgen>=2023 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from matminer) (2026.5.4)
Requirement already satisfied: scipy>=1.17.0 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from matminer) (1.17.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas<3,>=1.5->matminer) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas<3,>=1.5->matminer) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas<3,>=1.5->matminer) (2025.2)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo~=4.5->matminer)
  Using cached dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests~=2.31->matminer) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests~=2.31->matminer) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from requests~=2.31->matminer) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from requests~=2.31->matminer) (2025.11.12)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from scikit-learn~=1.3->matminer) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from scikit-learn~=1.3->matminer) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from sympy~=1.11->matminer) (1.3.0)
Requirement already satisfied: ruamel.yaml in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from monty>=2023->matminer) (0.19.1)
Requirement already satisfied: pymatgen-core>=2026.4.16 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from pymatgen>=2023->matminer) (2026.5.18)
Requirement already satisfied: bibtexparser in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (1.4.4)
Requirement already satisfied: lxml>=6.1.0 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (6.1.1)
Requirement already satisfied: matplotlib>=3.8 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (3.10.6)
Requirement already satisfied: networkx>=2.7 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (3.5)
Requirement already satisfied: orjson<4,>=3.10 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (3.11.9)
Requirement already satisfied: palettable>=3.3.3 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (3.3.3)
Requirement already satisfied: plotly>=6.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (6.5.0)
Requirement already satisfied: spglib>=2.5 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (2.7.0)
Requirement already satisfied: tabulate>=0.9.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (0.9.0)
Requirement already satisfied: uncertainties>=3.1 in /home/8e7da375-1215-4ce7-8157-c0b4225d40b7/.local/lib/python3.12/site-packages (from pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (3.2.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (25.0)
Requirement already satisfied: pillow>=8 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from matplotlib>=3.8->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from plotly>=6.0->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (2.7.0)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.5->matminer) (1.17.0)
Requirement already satisfied: typing-extensions>=4.9.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from spglib>=2.5->pymatgen-core>=2026.4.16->pymatgen>=2023->matminer) (4.15.0)
Using cached matminer-0.10.1-py3-none-any.whl (5.3 MB)
Using cached pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
Using cached dnspython-2.8.0-py3-none-any.whl (331 kB)
Installing collected packages: dnspython, pymongo, matminer
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [matminer]━━━ 2/3 [matminer]
Successfully installed dnspython-2.8.0 matminer-0.10.1 pymongo-4.17.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
df = pd.read_csv("Cleaned_Data.csv")

In [23]:
df.head(10)

   Temperature              Formula        ZT
0          350  Pb0.7Mn0.3Te1Na0.04  0.276253
1          400  Pb0.7Mn0.3Te1Na0.04  0.420050
2          450  Pb0.7Mn0.3Te1Na0.04  0.563897
3          500  Pb0.7Mn0.3Te1Na0.04  0.689989
4          550  Pb0.7Mn0.3Te1Na0.04  0.799702
5          600  Pb0.7Mn0.3Te1Na0.04  0.897287
6          650  Pb0.7Mn0.3Te1Na0.04  0.987101
7          700  Pb0.7Mn0.3Te1Na0.04  1.117313
8          350   Pb0.98Na0.02Te1ISW  0.178594
9          400   Pb0.98Na0.02Te1ISW  0.322591

In [24]:
from pymatgen.core import Composition

df["composition"] = df["Formula"].apply(Composition)

In [25]:
df

      Temperature                  Formula        ZT       composition
0             350      Pb0.7Mn0.3Te1Na0.04  0.276253  (Pb, Mn, Te, Na)
1             400      Pb0.7Mn0.3Te1Na0.04  0.420050  (Pb, Mn, Te, Na)
2             450      Pb0.7Mn0.3Te1Na0.04  0.563897  (Pb, Mn, Te, Na)
3             500      Pb0.7Mn0.3Te1Na0.04  0.689989  (Pb, Mn, Te, Na)
4             550      Pb0.7Mn0.3Te1Na0.04  0.799702  (Pb, Mn, Te, Na)
...           ...                      ...       ...               ...
1175          550  Na0.015Pb0.955Cd0.03Te1  0.982589  (Na, Pb, Cd, Te)
1176          600  Na0.015Pb0.955Cd0.03Te1  1.228149  (Na, Pb, Cd, Te)
1177          650  Na0.015Pb0.955Cd0.03Te1  1.438621  (Na, Pb, Cd, Te)
1178          700  Na0.015Pb0.955Cd0.03Te1  1.587491  (Na, Pb, Cd, Te)
1179          750  Na0.015Pb0.955Cd0.03Te1  1.657323  (Na, Pb, Cd, Te)

[1180 rows x 4 columns]

In [26]:
df["composition"]

0       (Pb, Mn, Te, Na)
1       (Pb, Mn, Te, Na)
2       (Pb, Mn, Te, Na)
3       (Pb, Mn, Te, Na)
4       (Pb, Mn, Te, Na)
              ...
1175    (Na, Pb, Cd, Te)
1176    (Na, Pb, Cd, Te)
1177    (Na, Pb, Cd, Te)
1178    (Na, Pb, Cd, Te)
1179    (Na, Pb, Cd, Te)
Name: composition, Length: 1180, dtype: object

In [27]:
from matminer.featurizers.composition import ElementProperty

featurizer = ElementProperty.from_preset("magpie")

In [28]:
df_features = featurizer.featurize_dataframe(
    df,
    col_id="composition",
    ignore_errors=True
)

ElementProperty:   0%|          | 0/1180 [00:00<?, ?it/s]

In [30]:
df_features

,Temperature,Formula,ZT,composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,350,Pb0.7Mn0.3Te1Na0.04,0.276253,"(Pb, Mn, Te, Na)",11.0,82.0,71.0,57.519608,16.800269,52.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
1,400,Pb0.7Mn0.3Te1Na0.04,0.420050,"(Pb, Mn, Te, Na)",11.0,82.0,71.0,57.519608,16.800269,52.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
2,450,Pb0.7Mn0.3Te1Na0.04,0.563897,"(Pb, Mn, Te, Na)",11.0,82.0,71.0,57.519608,16.800269,52.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
3,500,Pb0.7Mn0.3Te1Na0.04,0.689989,"(Pb, Mn, Te, Na)",11.0,82.0,71.0,57.519608,16.800269,52.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
4,550,Pb0.7Mn0.3Te1Na0.04,0.799702,"(Pb, Mn, Te, Na)",11.0,82.0,71.0,57.519608,16.800269,52.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,550,Na0.015Pb0.955Cd0.03Te1,0.982589,"(Na, Pb, Cd, Te)",11.0,82.0,71.0,65.957500,15.320588,52.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1176,600,Na0.015Pb0.955Cd0.03Te1,1.228149,"(Na, Pb, Cd, Te)",11.0,82.0,71.0,65.957500,15.320588,52.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1177,650,Na0.015Pb0.955Cd0.03Te1,1.438621,"(Na, Pb, Cd, Te)",11.0,82.0,71.0,65.957500,15.320588,52.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1178,700,Na0.015Pb0.955Cd0.03Te1,1.587491,"(Na, Pb, Cd, Te)",11.0,82.0,71.0,65.957500,15.320588,52.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1179,750,Na0.015Pb0.955Cd0.03Te1,1.657323,"(Na, Pb, Cd, Te)",11.0,82.0,71.0,65.957500,15.320588,52.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0

* So, here we are getting in total 132 vector features.

In [31]:
df_features.shape

(1180, 136)

In [33]:
df_features.columns

Index(['Temperature', 'Formula', 'ZT', 'composition',
       'MagpieData minimum Number', 'MagpieData maximum Number',
       'MagpieData range Number', 'MagpieData mean Number',
       'MagpieData avg_dev Number', 'MagpieData mode Number',
       ...
       'MagpieData range GSmagmom', 'MagpieData mean GSmagmom',
       'MagpieData avg_dev GSmagmom', 'MagpieData mode GSmagmom',
       'MagpieData minimum SpaceGroupNumber',
       'MagpieData maximum SpaceGroupNumber',
       'MagpieData range SpaceGroupNumber', 'MagpieData mean SpaceGroupNumber',
       'MagpieData avg_dev SpaceGroupNumber',
       'MagpieData mode SpaceGroupNumber'],
      dtype='object', length=136)

In [87]:

X = df_features.drop(columns=["Formula","composition","ZT"]) # Removing no-numeric columns

Y = df_features["ZT"]

In [88]:
X

,Temperature,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,350,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
1,400,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
2,450,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
3,500,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
4,550,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,550,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1176,600,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1177,650,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1178,700,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1179,750,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0

In [89]:
Y

0       0.276253
1       0.420050
2       0.563897
3       0.689989
4       0.799702
          ...
1175    0.982589
1176    1.228149
1177    1.438621
1178    1.587491
1179    1.657323
Name: ZT, Length: 1180, dtype: float64

In [90]:
X.isnull().sum()
# no. of missing values in each columns

Temperature                             0
MagpieData minimum Number              25
MagpieData maximum Number              25
MagpieData range Number                25
MagpieData mean Number                 25
                                       ..
MagpieData maximum SpaceGroupNumber    25
MagpieData range SpaceGroupNumber      25
MagpieData mean SpaceGroupNumber       25
MagpieData avg_dev SpaceGroupNumber    25
MagpieData mode SpaceGroupNumber       25
Length: 133, dtype: int64

In [91]:
missing = X.isnull().sum()

print(missing[missing == 25])

MagpieData minimum Number              25
MagpieData maximum Number              25
MagpieData range Number                25
MagpieData mean Number                 25
MagpieData avg_dev Number              25
                                       ..
MagpieData maximum SpaceGroupNumber    25
MagpieData range SpaceGroupNumber      25
MagpieData mean SpaceGroupNumber       25
MagpieData avg_dev SpaceGroupNumber    25
MagpieData mode SpaceGroupNumber       25
Length: 132, dtype: int64

All the feature columns are having 25 missing values. So, that's why we will use median imputation as missing values are few as compared to total no. of 
rows.

In [93]:
X = X.fillna(X.median())

In [94]:
X.isnull().sum()

Temperature                            0
MagpieData minimum Number              0
MagpieData maximum Number              0
MagpieData range Number                0
MagpieData mean Number                 0
                                      ..
MagpieData maximum SpaceGroupNumber    0
MagpieData range SpaceGroupNumber      0
MagpieData mean SpaceGroupNumber       0
MagpieData avg_dev SpaceGroupNumber    0
MagpieData mode SpaceGroupNumber       0
Length: 133, dtype: int64

In [101]:
Y.shape

(1180,)

In [100]:
X.shape

(1180, 133)

In [96]:
# save the feature matrix

feature_df = X.copy()
feature_df["ZT"] = Y

feature_df.to_csv(
    "Magpie_Features.csv",
    index=False
)

In [102]:
df

      Temperature                  Formula        ZT       composition
0             350      Pb0.7Mn0.3Te1Na0.04  0.276253  (Pb, Mn, Te, Na)
1             400      Pb0.7Mn0.3Te1Na0.04  0.420050  (Pb, Mn, Te, Na)
2             450      Pb0.7Mn0.3Te1Na0.04  0.563897  (Pb, Mn, Te, Na)
3             500      Pb0.7Mn0.3Te1Na0.04  0.689989  (Pb, Mn, Te, Na)
4             550      Pb0.7Mn0.3Te1Na0.04  0.799702  (Pb, Mn, Te, Na)
...           ...                      ...       ...               ...
1175          550  Na0.015Pb0.955Cd0.03Te1  0.982589  (Na, Pb, Cd, Te)
1176          600  Na0.015Pb0.955Cd0.03Te1  1.228149  (Na, Pb, Cd, Te)
1177          650  Na0.015Pb0.955Cd0.03Te1  1.438621  (Na, Pb, Cd, Te)
1178          700  Na0.015Pb0.955Cd0.03Te1  1.587491  (Na, Pb, Cd, Te)
1179          750  Na0.015Pb0.955Cd0.03Te1  1.657323  (Na, Pb, Cd, Te)

[1180 rows x 4 columns]

In [107]:
df["Formula"].nunique()

139

* so, there are in total 139 unique compounds and we have to split the test and train set by unique compounds.

In [108]:
unique_compounds = df["Formula"].unique()

In [113]:
len(unique_compounds)

139

In [112]:
unique_compounds[:10]

array(['Pb0.7Mn0.3Te1Na0.04', 'Pb0.98Na0.02Te1ISW', 'Pb1Te1Na0.04',
       'Pb1Te0.88S0.12', 'Pb1.00075Zn0.01Te1.01I0.0015',
       'Pb0.97Ce0.03Te1', 'Pb0.999La0.001Te1', 'Pb0.98Na0.02Te1LNSPS',
       'Na0.0125Pb0.9875Se1', 'Pb0.99Na0.01Te1'], dtype=object)

In [ ]:
# now splitting of training and test set using Scikit learn

from sklearn.model_selection import train_test_split

train_compounds, test_compounds = train_test_split(
    unique_compounds,
    test_size=0.20,
    random_state=42
)

In [118]:
print(len(train_compounds))
print(len(test_compounds))

111
28

In [121]:
# Create Masks to get the actual rows for test and train compounds
train_mask = df["Formula"].isin(train_compounds)
test_mask = df["Formula"].isin(test_compounds)
#boolean arrays

In [124]:
X_train = X[train_mask]
Y_train = Y[train_mask]
X_test = X[test_mask]
Y_test = Y[test_mask]

In [125]:
X_train

,Temperature,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,350,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
1,400,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
2,450,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
3,500,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
4,550,11.0,82.0,71.0,57.519608,16.800269,52.0,2.0,90.0,88.0,...,0.00031,0.000046,0.000078,0.0,152.0,229.0,77.0,188.117647,35.409458,152.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,550,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1176,600,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1177,650,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1178,700,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0
1179,750,11.0,82.0,71.0,65.957500,15.320588,52.0,2.0,90.0,88.0,...,0.00000,0.000000,0.000000,0.0,152.0,229.0,77.0,188.065000,36.065000,152.0

In [127]:
X_test

,Temperature,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
35,350,30.0,82.0,52.0,66.738039,15.10536,52.0,69.0,96.0,27.0,...,0.0,0.0,0.0,0.0,64.0,225.0,161.0,188.267895,36.411893,152.0
36,400,30.0,82.0,52.0,66.738039,15.10536,52.0,69.0,96.0,27.0,...,0.0,0.0,0.0,0.0,64.0,225.0,161.0,188.267895,36.411893,152.0
37,450,30.0,82.0,52.0,66.738039,15.10536,52.0,69.0,96.0,27.0,...,0.0,0.0,0.0,0.0,64.0,225.0,161.0,188.267895,36.411893,152.0
38,500,30.0,82.0,52.0,66.738039,15.10536,52.0,69.0,96.0,27.0,...,0.0,0.0,0.0,0.0,64.0,225.0,161.0,188.267895,36.411893,152.0
39,550,30.0,82.0,52.0,66.738039,15.10536,52.0,69.0,96.0,27.0,...,0.0,0.0,0.0,0.0,64.0,225.0,161.0,188.267895,36.411893,152.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,600,34.0,82.0,48.0,62.500000,19.50000,82.0,81.0,90.0,9.0,...,0.0,0.0,0.0,0.0,14.0,225.0,211.0,154.000000,71.000000,225.0
1148,650,34.0,82.0,48.0,62.500000,19.50000,82.0,81.0,90.0,9.0,...,0.0,0.0,0.0,0.0,14.0,225.0,211.0,154.000000,71.000000,225.0
1149,700,34.0,82.0,48.0,62.500000,19.50000,82.0,81.0,90.0,9.0,...,0.0,0.0,0.0,0.0,14.0,225.0,211.0,154.000000,71.000000,225.0
1150,750,34.0,82.0,48.0,62.500000,19.50000,82.0,81.0,90.0,9.0,...,0.0,0.0,0.0,0.0,14.0,225.0,211.0,154.000000,71.000000,225.0
1151,800,34.0,82.0,48.0,62.500000,19.50000,82.0,81.0,90.0,9.0,...,0.0,0.0,0.0,0.0,14.0,225.0,211.0,154.000000,71.000000,225.0

In [128]:
# to check the data leakage 
train_formulas = set(df.loc[train_mask,"Formula"])

test_formulas = set(df.loc[test_mask,"Formula"])

train_formulas.intersection(test_formulas)

set()

So, this indicates the split of train and test is done without any leakage

In [130]:
print(X_train.shape)
print(X_test.shape)

print(Y_train.shape)
print(Y_test.shape)

(948, 133)
(232, 133)
(948,)
(232,)

In [135]:
X_train.to_csv("x_train.csv", index = False)
X_test.to_csv("x_test.csv",index = False)
Y_test.to_csv("y_test.csv",index = False)
Y_train.to_csv("y_train.csv",index = False)

In [136]:
import pickle

with open("compound_split.pkl", "wb") as f:
    pickle.dump((train_compounds, test_compounds), f)